modified:   ../bin/hun_macro - grep make it work with more locales modified:   ../bin/hun_test - dunno modified:   Makefile modified:   hun_abbrev.flex.m4 modified:   hun_abbrev_en.flex.m4 modified:   hun_clean.flex modified:   hun_latin1.flex modified:   hun_sentbreak.flex modified:   hun_sentclean.flex modified:   hun_sentence.flex modified:   hun_token.flex - made all compilable on a regular 2013 environment

diff --git a/bin/hun_test b/bin/hun_test
--- a/bin/hun_test
+++ b/bin/hun_test
@@ -8,16 +8,15 @@ case $# in
     exit 1;
 esac
 
-echo -n "$1 tesztelése... "
+echo -n "testing $1 ..."
 
-temp="$(basename $2)"
-
-grep '/* BE:' $2 | sed 's#^[^/]*/\* BE: \(.*\) \*/.*#\1#' >$3/$temp.BE
+temp=`basename $2`
+grep '/* BE:' $2 | sed 's/^[^\/]*\/\* BE: //' | sed 's/\ \*\/.*//' >$3/$temp.BE
 $1 <$3/$temp.BE >$3/$temp.FILTERED
-grep '/* KI:' $2 | sed 's#^[^/]*/\* KI: \(.*\) \*/.*#\1#' >$3/$temp.KI
+grep '/* KI:' $2 | sed 's/^[^\/]*\/\* KI: //' | sed 's/\ \*\/.*//' >$3/$temp.KI
 
-diff $3/$temp.FILTERED $3/$temp.KI >$3/$temp.diff && echo "Jó!" || (
-echo 'Rossz!'
+diff $3/$temp.FILTERED $3/$temp.KI >$3/$temp.diff && echo "Success!" || (
+echo 'FAILED'
 cat $3/$temp.diff
 exit 1
 )
