modified:   ../bin/hun_test - mktemp

diff --git a/bin/hun_test b/bin/hun_test
--- a/bin/hun_test
+++ b/bin/hun_test
@@ -10,13 +10,19 @@ esac
 
 echo -n "testing $1 ..."
 
-temp=`basename $2`
-grep '/* BE:' $2 | sed 's/^[^\/]*\/\* BE: //' | sed 's/\ \*\/.*//' >$3/$temp.BE
-$1 <$3/$temp.BE >$3/$temp.FILTERED
-grep '/* KI:' $2 | sed 's/^[^\/]*\/\* KI: //' | sed 's/\ \*\/.*//' >$3/$temp.KI
+input=`mktemp`
+filtered=`mktemp`
+output=`mktemp`
+grep '/* BE:' $2 | sed 's/^[^\/]*\/\* BE: //' | sed 's/\ \*\/.*//' >$input
+$1 <$input >$filtered
+grep '/* KI:' $2 | sed 's/^[^\/]*\/\* KI: //' | sed 's/\ \*\/.*//' >$output
 
-diff $3/$temp.FILTERED $3/$temp.KI >$3/$temp.diff && echo "Success!" || (
-echo 'FAILED'
-cat $3/$temp.diff
-exit 1
+d=`mktemp`
+diff $filtered $output >$d && echo "Success!" || (
+  echo 'FAILED'
+  cat $d
+  rm $d $input $filtered $output
+  exit 1
 )
+
+rm $d $input $filtered $output
